version: 2.1

jobs:
  build-run:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo export NEEDRESTART_MODE=a
            sudo apt update
            sudo apt -y install python3-pip python3-setuptools
            sudo apt -y install qtbase5-dev libqt5svg5-dev
            sudo apt -y install libboost-dev libboost-regex-dev            
            sudo -H pip3 install conan
            conan profile detect
            conan remote add ess-dmsc https://artifactory.esss.lu.se/artifactory/api/conan/ecdc-conan-release
      - run:
          name: CMake
          command: |
            mkdir build && cd build
            cmake ..
      - run:
          name: Build
          command: |
            cmake --build ./build
      - run:
          name: Run
          command: |
            ./build/bin/nuclei -h

workflows:
  commit:
    jobs:
      - build-run
