version: 2.1

jobs:
  build-run:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            export NEEDRESTART_MODE=a
            sudo -E apt -y update
            sudo -E apt -y install python3-pip python3-setuptools qtbase5-dev libqt5svg5-dev libboost-dev libboost-regex-dev
            sudo -H pip3 install conan
            conan profile detect
            conan remote add ess-dmsc https://artifactory.esss.lu.se/artifactory/api/conan/ecdc-conan-release
      - run:
          name: CMake
          command: |
            mkdir build && cd build
            cmake ..
      - run:
          name: Build
          command: |
            cmake --build ./build --parallel 2
      - run:
          name: Run
          command: |
            ./build/bin/nuclei -h

workflows:
  commit:
    jobs:
      - build-run
