version: 2.1

jobs:
  build-run:
    parameters:
      build_type:
        type: string
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            export NEEDRESTART_MODE=a
            sudo -E apt -y update
            sudo -E apt -y install python3-pip python3-setuptools qtbase5-dev libqt5svg5-dev libboost-dev libboost-regex-dev
            sudo -H pip3 install conan
            conan profile detect
            conan remote add ess-dmsc https://artifactory.esss.lu.se/artifactory/api/conan/ecdc-conan-release
      - run:
          name: CMake-<<parameters.build_type>>
          command: |
            mkdir build && cd build
            cmake -DCMAKE_BUILD_TYPE=<<parameters.build_type>> ..
      - run:
          name: Build-<<parameters.build_type>>
          command: |
            cmake --build ./build --parallel 2
      - run:
          name: Run-<<parameters.build_type>>
          command: |
            ./build/bin/nuclei -h

workflows:
  commit:
    jobs:
      - build-run
          matrix:
            parameters:
              build_type: ["Debug", "Release"]
